### ISSUE TITLE
Не ставит пиксели, но запускается

### ISSUE THREAD

**Issue by Nikitka12XD** [hikinight/PixelX#12]
Все успешно загружается, но пиксели не хочет ставить ни в какую! 
Тестирую с помощью вашего же изображения который стоит в конфигах. (Версия скриптов последняя)
Один раз заработало, но переставало сразу, так же и с моим изображением.
Wss (У меня он один) постоянно менял, не помогало (Менял каждый раз и пробовал запустить скрипт: С открытым pixel battle и закрытым)

![image](https://user-images.githubusercontent.com/48694850/95660522-ae094900-0b52-11eb-90e1-7e4d0bf37fcc.png)

**Comment by MrCreepTon** [comment]
У меня все ок. Щас было очень много фиксов в течение этих часов, попробуй обновить файлы, которые были обновлены

**Comment by Nikitka12XD** [comment]
> У меня все ок. Щас было очень много фиксов в течение этих часов, попробуй обновить файлы, которые были обновлены

"Версия скриптов последняя", я все сразу обновлял, не помогло

**Comment by Nikitka12XD** [comment]
А хотя может версия node не та, попробую другие поставить, если не получится то открою issue

**Comment by Nikitka12XD** [comment]
Нет, не зависит от версии, проверил wss, рабочий.
Заметил одну особенность, при первом запуске все работает идеально, но при следующих все отказывается работать и стоит на одном месте.

**Comment by Nikitka12XD** [comment]
Толком js не знаю, только python, но по моему, все стопорится в:
```
      while (this.busy) {
        await this.sleep(500)
      }
```
core.js 35 строчка

**Comment by hikinight** [comment]
обновись до последней версии (?)

**Comment by hikinight** [comment]
просто оно стояло так, когда фикса не было...

**Comment by Nikitka12XD** [comment]
Сейчас пытался выловить где луп происходит, но тут же все заработало (пысы стояли последние версии скриптов, даже перекачивал, надеясь что просто что то повредилось)
![image](https://user-images.githubusercontent.com/48694850/95661862-fa598680-0b5c-11eb-801c-6c852339a8ff.png)
