### ISSUE TITLE
После пункта "Подключение к WebSocket было успешным." ничего не происходит (macOS)

### ISSUE THREAD

**Issue by MrMacduckinson** [hikinight/PixelX#13]
После запуска бота не происходит никаких действий после пункта "Подключение к WebSocket было успешным." в терминале. Пиксели не ставятся.
<img width="469" alt="Снимок экрана 2020-10-10 в 22 36 30" src="https://user-images.githubusercontent.com/49838563/95663577-0b989800-0b49-11eb-9b91-724254d63c54.png">

**Comment by TheAndrey** [comment]
Запускаете не самым правильным образом. Поэтому может файлы конфига не находит.
Перейдите в директорию с помощью `cd` и затем запускайте, указав только имя скрипта.

**Comment by iriswolf** [comment]
Запускайте из рабочей директории
