### ISSUE TITLE
Ошибка при попытки послать пиксель.

### ISSUE THREAD

**Issue by DSolo03** [hikinight/PixelX#14]
`(node:1384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at PixelBot.sendPixel (F:\pix\pix2\PixelX\PixelX\PixelX\core.js:71:24)
    at PixelBot.startWork (F:\pix\pix2\PixelX\PixelX\PixelX\core.js:90:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Возникает в этом участке кода
`const coords = ind.split(',')`
в файле core.js

-------------------------------
UPD
Путем отладки, я выяснил, что бот во всех картинках бот видит одну с кучей пикселей одинакого цвета `[ 122, 97, 181 ]`

**Comment by Ar4ikov** [comment]
@DSolo03, Как ты решил данную проблему?

**Comment by DSolo03** [comment]
> @DSolo03, Как ты решил данную проблему?

Пока никак. Но я продвинулся в отладке. На выходе, все изображения почему то убого сжатые

**Comment by MrCreepTon** [comment]
Проблема с координатами действительно есть. Что касаемо ошибки, мне помог последний коммит. Может быть тебе тоже поможет.

**Comment by Lewpik** [comment]
> > @DSolo03, Как ты решил данную проблему?
> 
> Пока никак. Но я продвинулся в отладке. На выходе, все изображения почему то убого сжатые. Потому что бот уменьшает изображение в 2.3 раза.А точнее получает его таким

у меня такая же ошибка 
![image](https://user-images.githubusercontent.com/72683019/95672981-7690b000-0bd7-11eb-8c20-5da3363b03f1.png)
ты смог от нее избавиться?

**Comment by Lewpik** [comment]
> Проблема с координатами действительно есть. Что касаемо ошибки, мне помог последний коммит. Может быть тебе тоже поможет.

какой коммит?

**Comment by shardeex** [comment]
Плюсую, возникает такая же ошибка, однако при добавлении лишь одного аккаунта всё работает нормально.
![Снимок экрана от 2020-10-11 13-57-37](https://user-images.githubusercontent.com/54213170/95676848-d5e7c380-0bc9-11eb-8496-a6b09079ecdc.png)

**Comment by iriswolf** [comment]
Решили?

**Comment by DSolo03** [comment]
Я выяснил в чем проблема. При говнянном хостинге,бот скачивает изображение в говнянном разрешении. из-за этого не видит знакомых пикслей и в ошибку уходит

**Comment by shardeex** [comment]
Нет. Один из аккаунтов работает прекрасно.

**Comment by PerchunPak** [comment]
попробуйте хостинг https://oshi.at он не сжимает изображение, и лично у меня все прекрасно с ним

**Comment by shardeex** [comment]
> попробуйте хостинг https://oshi.at он не сжимает изображение, и лично у меня все прекрасно с ним
> 

Проблема осталась. Увы.

**Comment by keyfqsY** [comment]
Дело в том, что ты "разукрасил" пиксель в цвет, который не поддерживается скриптом. Используй таблицу цветов, которая не посредственна есть в коде.
