### ISSUE TITLE
Ошибка Unexpected token ]

### ISSUE THREAD

**Issue by Lewpik** [hikinight/PixelX#16]
После запуска бота, выдает одну и ту же ошибку каждый раз "SyntaxError: C:\Users\nikit\Desktop\PixelX-master\config.json: Unexpected token ] in JSON at position 3404
    at parse (<anonymous>)"

![image](https://user-images.githubusercontent.com/72683019/95671582-74285900-0bcb-11eb-86a0-36456dbede78.png)

**Comment by MrCreepTon** [comment]
Скорее всего некорректно где-то закрыл json конфиг.

**Comment by Lewpik** [comment]
> Скорее всего некорректно где-то закрыл json конфиг.

![image](https://user-images.githubusercontent.com/72683019/95672348-a5f0ee00-0bd2-11eb-94c0-795b0857537a.png)
в каком смысле некорректно закрыл то?

**Comment by hikinight** [comment]
лишняя запятая в конфиге где-то
