### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by Lewpik** [hikinight/PixelX#17]
![image](https://user-images.githubusercontent.com/72683019/95672427-3b8c7d80-0bd3-11eb-91ee-75732c8aa444.png)
после запуска вот такая ошибка

**Comment by Drauiq** [comment]
Проблема на вашей стороне. Возможно, canvas не смог установиться (см. Гугл), либо вы не дождались закрытия install.bat.

**Comment by hikinight** [comment]
дубликат #1
