### ISSUE TITLE
Ошибка RangeError

### ISSUE THREAD

**Issue by Nikitka12XD** [hikinight/PixelX#18]
Уже не в первые, очень мешает.

![image](https://user-images.githubusercontent.com/48694850/95677525-3d186e80-0bf0-11eb-9756-abdaef3e816f.png)

**Comment by iriswolf** [comment]
Какая версия ноды?

**Comment by Nikitka12XD** [comment]
Стабильная 12.19.0

**Comment by iriswolf** [comment]
Формат картинки какой используешь?
И что-то менял кроме config.json?

**Comment by Nikitka12XD** [comment]
Оказалось залил на сервер не ту версию скрипта, прошу прощение)

**Comment by iriswolf** [comment]
окей
