### ISSUE TITLE
Ошибка при запуске бота

### ISSUE THREAD

**Issue by majehoff** [hikinight/PixelX#19]
![image](https://user-images.githubusercontent.com/72693111/95677902-9a50f780-0bd1-11eb-8d58-b1bf483329ba.png)
Происходит данная ошибка при запуске бота. В чем связана проблема арт залит, аккаунты в вк так же

**Comment by Nikitka12XD** [comment]
json файл поломан

**Comment by iriswolf** [comment]
Покажи ка config.json

**Comment by hikinight** [comment]
json невалиден, запусти валидатор Json - может, где-то запятая пропущена
