### ISSUE TITLE
Ошибка при добавлении второго аккаунта

### ISSUE THREAD

**Issue by iriswolf** [hikinight/PixelX#20]
`(node:5080) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at PixelBot.sendPixel (C:\Users\iris\Desktop\PixelX-master\core.js:70:24)
    at PixelBot.startWork (C:\Users\iris\Desktop\PixelX-master\core.js:89:16)
(node:5080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which w
as not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:5080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit co
de.`

Такая ошибка появляется при использовании более 1 аккаунта

**Comment by shardeex** [comment]
Подтверждаю!
![Снимок экрана от 2020-10-11 13-57-37](https://user-images.githubusercontent.com/54213170/95679515-0cc6d500-0bdc-11eb-8c38-d97f90473d43.png)

**Comment by iriswolf** [comment]
@hikinight А можно хотя бы как-то прокомментировать? :/

**Comment by hikinight** [comment]
> @hikinight А можно хотя бы как-то прокомментировать? :/

1. я сплю
2. в версии, которую я выпустил 5 часов назад (что раньше твоего сообщения на 1 час) выбранные строки не относятся к какому-либо коду.
3. если знаете фикс - welcome to the PR

**Comment by hikinight** [comment]
может быть, дело в картинке, кто знает

**Comment by shardeex** [comment]
Картинка залита мною на разные хостинги, в документы в вк, на имгур. Всё одно — один аккаунт пашет, другие (в моём случае ещё два) — нет. Картинка нужно размера, с прозрачным фоном, хостом не шакалится. Увы, не знаю node.js, потому помочь с кодом не могу. Но хотела бы.

**Comment by iriswolf** [comment]
@hikinight 
Ержан, вставай, тут у людей баги
Чего спишь в 8 вечера
1. Не в картинке, вопрос с картинкой я решил, была проблема
2. У меня скачена последняя версия бота

**Comment by nitreojs** [comment]
> 
> 
> @hikinight
> Ержан, вставай, тут у людей баги
> Чего спишь в 8 вечера
> 
>     1. Не в картинке, вопрос с картинкой я решил, была проблема
> 
>     2. У меня скачена последняя версия бота

скиньте **70** и **89** строку (и все, что около них) вашего файла `core.js`

**Comment by iriswolf** [comment]
Зря быканул
Исправил кое что

**Comment by nitreojs** [comment]
что именно?
