### ISSUE TITLE
Ошибка при запуске.

### ISSUE THREAD

**Issue by Kovtan** [hikinight/PixelX#21]
Error: Cannot find module 'canvas'
Require stack:
- D:\PixelX-master\store.js
- D:\PixelX-master\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:903:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (D:\PixelX-master\store.js:2:33)
[90m    at Module._compile (internal/modules/cjs/loader.js:1015:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:879:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:903:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'D:\\PixelX-master\\store.js'[39m, [32m'D:\\PixelX-master\\index.js'[39m ]
}

**Comment by shardeex** [comment]
bash install.sh

**Comment by Kovtan** [comment]
> bash install.sh
> или батник запусти, если Windows

да запускал, походу канвас не установился, откуда скачивать?

**Comment by shardeex** [comment]
честно говоря, я сама не знаю, ибо нет знания языка. просто я по глупости тоже сразу же start.sh запускала, забыв про установку. жаль, что не смогла помочь :с

**Comment by Kovtan** [comment]
> честно говоря, я сама не знаю, ибо нет знания языка. просто я по глупости тоже сразу же start.sh запускала, забыв про установку. жаль, что не смогла помочь :с
да ничего)
сам не шарю да

**Comment by hikinight** [comment]
не установлен canvas, если впервые устанавливал node.js - перезапусти компьютер;
удали папку node_modules (если есть) и запусти install.bat/.sh
