### ISSUE TITLE
Не фатальная ошибка

### ISSUE THREAD

**Issue by Nidelon** [hikinight/PixelX#29]
Ошибка иногда появляется, но нервирует, не фатальная, скрипт продолжает работать

![image](https://user-images.githubusercontent.com/48694850/95740202-4a982c00-0cb6-11eb-9268-09465d7cba95.png)

**Comment by raywave** [comment]
При запросе картинки скрипт получает ответ "не найдено".

**Comment by Nidelon** [comment]
Не понимаю смысла постоянно опрашивать картинку, ну да ладно
