### ISSUE TITLE
Пишет, что нарисовал пиксели а на самом табло их нет 

### ISSUE THREAD

**Issue by spitsynv2** [hikinight/PixelX#30]
![1](https://user-images.githubusercontent.com/61032832/95749697-465f1500-0c9c-11eb-9408-5edc84296861.PNG)

**Comment by keyfqsY** [comment]
та-же проблема

**Comment by raywave** [comment]
Во время тестов не удалось повторить бага, пока закрою. Если найдете способ повторить баг - отпишитесь в теме.
